### PR TITLE
Add models based on ERD

### LINKED ISSUE #10: Add models

### PR DESCRIPTION
**Pull request by joshdavies14**
Closes #10 - matches up to ERD?, feel free to comment here or in Discord, and I can adjust. If we are happy I will create the migrations before merging. :)

### CODE REVIEW

**Review by NoahNok — COMMENTED** [review]
I have made changes, do we know if django supports polymorphic relations?

**Comment by NoahNok** [comment]
> 

We can use ContentType

**Comment by NoahNok** [comment]
Added content type. Still needs testing though to make sure migrations generate properly!

**Review by NoahNok — APPROVED** [review]
Happy to PR if all works as expected! (Hs the migrations been tested when run in postgres?)

**Comment by joshdavies14** [comment]
Running `python manage.py migrate` worked so I guess it's happy :P I'll do a separate PR for Cypress at some point in the next week but I think I'm happy to merge this one if others are :)

**Comment by joshdavies14** [comment]
Just for clarity I've just added a base HTML template copied over from one of my other projects, and updated the existing templates to use that. We will obviously want to change the colour scheme/add logos etc, but this can serve as a base for front-end work :)

**Pull request merged**
